apiVersion: v2
name: outline
description: The outline helm chart to deploy outline in kubernetes clusters.
version: 2.3.0
appVersion: 1.5.0
home: https://getoutline.com
sources:
  - https://github.com/lrstanley/helm-charts
keywords:
  - chart
  - helm
  - knowledge
  - kubernetes
  - minio
  - outline
  - postgresql
  - redis
  - s3
  - wiki
maintainers:
  - name: lrstanley
    email: liam@liam.sh
    url: https://liam.sh
dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 16.7.4
    condition: postgresql.enabled
  - name: minio
    repository: https://charts.bitnami.com/bitnami
    version: 16.0.10
    condition: minio.enabled
  - name: dex
    repository: https://charts.dexidp.io
    version: 0.24.0
    condition: dex.enabled
