apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "outline.fullname" . }}
  labels:
    {{- include "outline.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "outline.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- /* checksums, which ensure that if anything changes (that might not recreate the pods) will force recreate the pods */}}
        checksum/environment: {{ toYaml .Values.environment | sha256sum }}
        {{- if and .Values.redis.enabled .Values.redis.auth.enabled .Values.redis.auth.generate }}
        checksum/redis-generated-credentials: {{ include (print $.Template.BasePath "/secret_redis_credentials.yaml") . | sha256sum }}
        {{- end }}
        checksum/redis-auth: {{ toYaml .Values.redis.auth | sha256sum }}
        {{- if and .Values.postgresql.enabled .Values.postgresql.auth.generate }}
        checksum/postgresql-generated-credentials: {{ include (print $.Template.BasePath "/secret_postgresql_credentials.yaml") . | sha256sum }}
        {{- end }}
        checksum/postgresql-auth: {{ toYaml .Values.postgresql.auth | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "outline.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "outline.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: wait-for-services
          image: busybox:latest
          imagePullPolicy: Always
          command:
            - "sh"
            - "-c"
            - |
              {{- if .Values.postgresql.enabled }}
              until nc -w 5 -z {{ .Release.Name }}-postgresql {{ .Values.postgresql.primary.service.ports.postgresql }};do
                echo "waiting for postgresql"
                sleep 2
              done
              {{- end }}
              {{- if .Values.cnpg.enabled }}
              until nc -w 5 -z {{ include "outline.cnpgName" . }}-rw 5432;do
                echo "waiting for cnpg postgresql"
                sleep 2
              done
              {{- end }}
              {{- if .Values.redis.enabled }}
              until nc -w 5 -z {{ .Release.Name }}-redis-master {{ .Values.redis.master.service.ports.redis }};do
                echo "waiting for redis"
                sleep 2
              done
              {{- end }}
              {{- if .Values.minio.enabled }}
              until nc -w 5 -z {{ .Values.minio.apiIngress.hostname }} {{ if or .Values.minio.forceUrlAsHttps .Values.minio.apiIngress.tls }}443{{ else }}80{{ end }};do
                echo "waiting for minio"
                sleep 2
              done
              {{- end }}

              exit 0
        {{- with .Values.initContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name | quote }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{ with .Values.environmentFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{ end }}
          env:
            {{- include "outline.envs" . | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /_health
              port: http
            initialDelaySeconds: 5
            failureThreshold: 24
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /_health
              port: http
            initialDelaySeconds: 5
            failureThreshold: 2
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
