{{- if and .Values.redis.enabled .Values.redis.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-redis-data
  labels:
    {{- include "outline.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size | quote }}
  {{- if .Values.redis.persistence.storageClass }}
  storageClassName: {{ .Values.redis.persistence.storageClass | quote }}
  {{- end }}
{{- end }}
