{{- if and .Values.cnpg.enabled .Values.cnpg.auth.generate }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cnpg.auth.existingSecret | quote }}
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.cnpg.auth.username | b64enc | quote }}
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace .Values.cnpg.auth.existingSecret) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  password: {{ ((get $secretData "password") | default (randAlphaNum 64 | b64enc)) | quote }}
{{- end }}
