{{- if and .Values.redis.enabled .Values.redis.auth.enabled .Values.redis.auth.generate }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.redis.auth.existingSecret | quote }}
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace .Values.redis.auth.existingSecret) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $secret := ((get $secretData .Values.redis.auth.existingSecretPasswordKey | b64dec) | default (randAlphaNum 32)) }}
  {{ .Values.redis.auth.existingSecretPasswordKey }}: {{ $secret | b64enc | quote }}
  ioredis: {{ printf "ioredis://%s" (printf "{\"host\": \"%s-redis-master\", \"port\": %0.f, \"password\": %s}" .Release.Name .Values.redis.master.service.ports.redis ($secret | quote) | b64enc) | b64enc | quote }}
{{- end }}
