{{- if .Values.outline.generateEncryptionKeys }}
{{- $name := printf "%s-enc-keys" (include "outline.fullname" .) | trunc 63 | trimSuffix "-" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name | quote }}
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace $name) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  secret-key: {{ ((get $secretData "secret-key") | default (include "outline.randHex" 64 | b64enc)) | quote }}
  utils-secret: {{ ((get $secretData "utils-secret") | default (include "outline.randHex" 64 | b64enc)) | quote }}
{{- end }}
