{{- if and .Values.postgresql.enabled .Values.postgresql.auth.generate }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.auth.existingSecret | quote }}
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace .Values.postgresql.auth.existingSecret) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  postgres-password: {{ ((get $secretData "postgres-password") | default (randAlphaNum 64 | b64enc)) | quote }}
  password: {{ ((get $secretData "password") | default (randAlphaNum 64 | b64enc)) | quote }}
{{- end }}
