{{- if and .Values.minio.enabled .Values.minio.auth.generate }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.minio.auth.existingSecret | quote }}
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace .Values.minio.auth.existingSecret) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  root-user: {{ ((get $secretData "root-user") | default (randAlphaNum 32 | b64enc)) | quote }}
  root-password: {{ ((get $secretData "root-password") | default (randAlphaNum 64 | b64enc)) | quote }}
{{- end }}
