{{- if and .Values.redis.enabled .Values.redis.auth.enabled .Values.redis.auth.generate }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.redis.auth.existingSecret | quote }}
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace .Values.redis.auth.existingSecret) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{ .Values.redis.auth.existingSecretPasswordKey }}: {{ ((get $secretData .Values.redis.auth.existingSecretPasswordKey) | default (randAlphaNum 32 | b64enc)) | quote }}
{{- end }}
