{{- if not .Values.existingConfigSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "autodelete-discord.fullname" . }}-config
  labels:
    {{- include "autodelete-discord.labels" . | nindent 4 }}
type: Opaque
data:
  config.yml: {{ .Values.config | toYaml | b64enc | quote }}
{{- end }}
