apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "autodelete-discord.fullname" . }}
  labels:
    {{- include "autodelete-discord.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "autodelete-discord.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "autodelete-discord.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "autodelete-discord.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "autodelete-discord.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 2202
              name: http
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
          volumeMounts:
            - name: data
              mountPath: /autodelete/data
            - name: config
              mountPath: /autodelete
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          secret:
            {{- if .Values.existingConfigSecret }}
            secretName: {{ .Values.existingConfigSecret | quote }}
            {{- else }}
            secretName: {{ include "autodelete-discord.fullname" . }}-config
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- else }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: autodelete-discord
                topologyKey: kubernetes.io/hostname
              weight: 100
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: data
      {{- with .Values.pvcTemplateSpec }}
      spec:
        {{- toYaml . | nindent 8 }}
      {{- end }}
