name: helm-version-updater

on:
  schedule:
    - cron: "0 13 * * *"
  workflow_dispatch: {}

jobs:
  helm-version-updater:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lrstanley/helm-version-updater@v0.0.2
        with:
          check-dir: tests/
