name: helm-version-updater

on:
  schedule:
    - cron: "0 13 * * *"
  workflow_dispatch: {}

jobs:
  action-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lrstanley/helm-version-updater@master
        with:
          check-dir: tests/
