name: helm-docs

on:
  push:
    branches: [master]

jobs:
  helm-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: generate
        continue-on-error: true
        run: |
          set -e

          for CHART in $(find charts/ -mindepth 1 -maxdepth 1 -type d -exec basename "{}" \;);do
            cp -av .github/HELM_README.md.gotmpl /tmp/HELM_README.md.gotmpl

            if [ -f "charts/${CHART}/HEADER.md" ]; then
              cat .github/HELM_README.md.gotmpl | awk \
                -v CONTENT="$(cat charts/${CHART}/HEADER.md)" \
                -v RS="template:begin:header .* template:end:header" \
                -v ORS= \
                '1;NR==1{print "template:begin:header -->\n" CONTENT "\n<!-- template:end:header"}' > /tmp/HELM_README.md.gotmpl
            fi

            docker run --rm \
              -v "$PWD:/helm-docs" \
              -v "/tmp/HELM_README.md.gotmpl:/tmp/HELM_README.md.gotmpl" \
              jnorwood/helm-docs:v1.12.0 \
              --chart-to-generate "charts/$CHART" \
              --template-files /tmp/HELM_README.md.gotmpl
          done

          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add --all
          git commit -m "chore(docs): regenerate helm readmes [skip ci]"
          git push
