name: helm-version-updater

on:
  schedule:
    - cron: "0 13 * * *"
  workflow_dispatch: {}

jobs:
  get-charts:
    runs-on: ubuntu-latest
    outputs:
      changeset: ${{ steps.updater.outputs.changeset }}
    steps:
      - uses: actions/checkout@v4
      - uses: lrstanley/helm-version-updater@master
        id: updater
        with:
          check-dir: charts/
          dry-run: true
  helm-version-updater:
    runs-on: ubuntu-latest
    needs: [get-charts]
    if: ${{ fromJSON(needs.get-charts.outputs.changeset).changes != null }}
    strategy:
      fail-fast: false
      matrix:
        change: ${{ fromJSON(needs.get-charts.outputs.changeset).changes }}
    steps:
      - uses: actions/checkout@v4
      - uses: lrstanley/helm-version-updater@master
        id: updater
        with:
          check-dir: ${{ matrix.change.path }}
      - name: create pr
        uses: peter-evans/create-pull-request@9153d834b60caba6d51c9b9510b087acf9f33f83
        with:
          token: ${{ secrets.USER_PAT }}
          add-paths: "${{ matrix.change.chart.path }}"
          title: >-
            update chart ${{ matrix.change.chart.name }}
            from ${{ matrix.change.old_version }}
            to ${{ matrix.change.new_version }}
          commit-message: >-
            chore(${{ matrix.change.chart.name }}): update chart
            from ${{ matrix.change.old_version }}
            to ${{ matrix.change.new_version }}
          body: |
            Updating chart `${{ matrix.change.chart.name }}`:

            - Bumping **version** from `${{ matrix.change.old_version }}` to `${{ matrix.change.new_version }}`.
            - Bumping **appVersion** from `${{ matrix.change.old_app_version }}` to `${{ matrix.change.new_app_version }}`.

            Pull request auto-generated by [helm-version-updater](https://github.com/lrstanley/helm-version-updater).
          signoff: true
          branch: "chore/version-updater/${{ matrix.change.chart.name }}"
          delete-branch: true
          base: master
          labels: "chore,chart,chart-${{ matrix.change.chart.name }}"
          assignees: "lrstanley"
