name: helm-version-updater

on:
  schedule:
    - cron: "0 13 * * *"
  workflow_dispatch: {}

jobs:
  helm-version-updater:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@0df5d9c641efdff149993c321fc27c11c5df8623
        with:
          deno-version: v1.x
      - run: deno run --allow-all ./helm-version-updater/main.ts
        env:
          GITHUB_TOKEN: ${{ secrets.USER_PAT }}
