name: release

on:
  push:
    branches: [master]
    paths-ignore: [".gitignore", "**/*.md", ".github/ISSUE_TEMPLATE/**"]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: git-config
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - uses: azure/setup-helm@b7246b12e77f7134dc2d460a3d5bad15bbe29390
        with:
          version: v3.14.4
      - name: helm-dependencies
        run: |
          while read -r chart;do
            cd "$chart" || exit 1

            while read -r name _ repo _;do
              [ -z "$repo" ] && continue
              (set -x; helm repo add "$name" "$repo")
            done <<<"$(helm dependency list 2>/dev/null | grep https)"
          done <<<"$(find "$PWD/charts/" -mindepth 1 -maxdepth 1 -type d)"
      - uses: helm/chart-releaser-action@a917fd15b20e8b64b94d9158ad54cd6345335584
        continue-on-error: false
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: true
